name: Docker Build & Container Scan (Trivy)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Node.js app image
        run: |
          docker build \
            -t pacman-nodejs:ci \
            -f docker/Dockerfile .

      - name: Run Trivy scan (app image)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'pacman-nodejs:ci'
          format: 'table'
          exit-code: '0' # set to 1 later if you want it to block
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Pull MongoDB 3.4 image
        run: docker pull mongo:3.4

      - name: Run Trivy scan (mongo image)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'mongo:3.4'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push app image (SHA tag)
        if: github.event_name == 'push'
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/pacman-nodejs:${{ github.sha }}"
          docker tag pacman-nodejs:ci "$IMAGE"
          docker push "$IMAGE"

